In [2]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
Using cached numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.2 pandas-3.0.5

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [ ]:
#판다스 프로그램 불러오기 
import pandas as pd

In [ ]:
#공항 데이터 만들기
airport_data ={
    '공항명' : ['김포', '제주', '김해', '대구', '인천'],
    '일일이용객' : [75000, 82000, 45000, 12000, 9000],
    '운항편수' : [400, 450, 250, 80, 60]

}

In [ ]:
#데이터를 표로 변환하기
df = pd.DataFrame(airport_data)

In [ ]:
#표 확인하기
df

  공항명  일일이용객  운항편수
0  김포  75000   400
1  제주  82000   450
2  김해  45000   250
3  대구  12000    80
4  인천   9000    60

In [10]:
#표의 가장 위쪽 3줄 미리보기
df.head(3)

  공항명  일일이용객  운항편수
0  김포  75000   400
1  제주  82000   450
2  김해  45000   250

In [11]:
#표의 전반적인 정보(줄 개수, 데이터 종류 등) 확인하기
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   공항명     5 non-null      str
 1   일일이용객   5 non-null      int64
 2   운항편수    5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [ ]:
#일일이용객이 5만 명이 넘는 공항만 필터링하기
busy_airports = df[df['일일이용객']>=50000]

In [13]:
#결과 확인
busy_airports

  공항명  일일이용객  운항편수
0  김포  75000   400
1  제주  82000   450