In [3]:
import pandas as pd
import numpy as np

#국내 주요 공항 운항 현황 가상 데이터 
data = {
    '공항명' : ['김포', '제주', '김해', '청주', '무안', '대구'],
    '일일이용객' : [75000, 82000, 45000, np.nan, 3000, 12000], #결측치 포함
    '지연건수' : [12, 5, 8, 2, 0, np.nan], #결측치 포함
    '혼잡도' : ['높음', '높음', '보통', '낮음' , '낮음' ,'보통']
}

df = pd.DataFrame(data)

#결과 확인
df

  공항명    일일이용객  지연건수 혼잡도
0  김포  75000.0  12.0  높음
1  제주  82000.0   5.0  높음
2  김해  45000.0   8.0  보통
3  청주      NaN   2.0  낮음
4  무안   3000.0   0.0  낮음
5  대구  12000.0   NaN  보통

In [4]:
#각 컬럼마다 빈칸이 몇 개 있는지 알아보기
df.isna().sum()

공항명      0
일일이용객    1
지연건수     1
혼잡도      0
dtype: int64

In [5]:
#'일일이용객'의 평균을 구해서 빈칸에 채워넣기
mean_passengers = df['일일이용객'].mean()
df['일일이용객'] = df['일일이용객'].fillna(mean_passengers)

#'지연건수'의 빈칸은 숫자 0으로 채워넣기
df['지연건수']=df['지연건수'].fillna(0)

#최종결과
df

  공항명    일일이용객  지연건수 혼잡도
0  김포  75000.0  12.0  높음
1  제주  82000.0   5.0  높음
2  김해  45000.0   8.0  보통
3  청주  43400.0   2.0  낮음
4  무안   3000.0   0.0  낮음
5  대구  12000.0   0.0  보통

# 결측치 탐지 및 처리 필수 함수 

## isna() 데이터 스캔
* 데이터 프레임 안에 값이 비어있는 곳(NaN)이 있는지 검사
* 비어있으면 'True' 값이 있으면 'False' 반환
* 데이터가 많을 때 보통 '.sum()' 함수와 같이 사용
* ex. 'df.isna().sum()'

## fillna(값) 데이터 복원 
* 빈칸(NaN)을 특정 값으로 덮어씌우기
* 0으로 채우거나 평균값으로 채우는 역할
* ex. 'df.fillna(0)', 'df['이용객'].fillna(mean)'

In [7]:
#'일일이용객'을 기준으로 내림차순 정렬
df_sorted = df.sort_values(by='일일이용객', ascending=False)

#결과 확인
df_sorted

  공항명    일일이용객  지연건수 혼잡도
1  제주  82000.0   5.0  높음
0  김포  75000.0  12.0  높음
2  김해  45000.0   8.0  보통
3  청주  43400.0   2.0  낮음
5  대구  12000.0   0.0  보통
4  무안   3000.0   0.0  낮음

# 데이터 정렬 필수 함수

## sort_values()
* **행 순서 재배치**
* by='컬럼명' -> 기준이 될 항목 
* ascending=True 오름차순(기본값) 
* ascending=False 내림차순 
* 보고서를 위한 순위표를 뽑아낼 때 많이 사용
* ex. 'df.sort_valuse(by='지연건수')' 
* -> 지연건수가 적은 순(오름차순)으로 정렬