In [1]:
import pandas as pd

# 공항의 일일 운항 및 이용객 데이터
data = {
    '공항명': ['김포', '제주', '김해', '청주'],
    '일일운항편수': [400, 480, 250, 50],
    '일일이용객': [75000, 84000, 45000, 6000]
}
df = pd.DataFrame(data)

df

  공항명  일일운항편수  일일이용객
0  김포     400  75000
1  제주     480  84000
2  김해     250  45000
3  청주      50   6000

In [2]:
#'일일이용객'을 '일일운항편수'로 나눠서 새로운 열 '편당_탑승객' 만들기
df['편당_탑승객']=df['일일이용객']/df['일일운항편수']

#반올림(round) 처리
df['편당_탑승객']=df['편당_탑승객'].round(0)

#결과물 확인
df

  공항명  일일운항편수  일일이용객  편당_탑승객
0  김포     400  75000   188.0
1  제주     480  84000   175.0
2  김해     250  45000   180.0
3  청주      50   6000   120.0

### 파생 변수(새로운 열) 만들기

#### df['새로운 열'] = 계산식 
* 사칙연산이나 함수를 통해 데이터를 만들어 냄 
* ex. (매출액)-(원가)='[순이익]' 
* **round(숫자)** 계산 결과가 지저분하게 나올 때 이용